### ISSUE TITLE
通过CDN引入库时后台报错

### ISSUE THREAD

**Issue by ZiuChen** [wangeditor-team/wangEditor-plugin-upload-attachment#1]
> 实在不好意思，又是我。

### 问题描述

我在通过CDN引入代码后浏览器后台报错：

`Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'i18nAddResources')`

### 复现方式

通过脚本管理器[`Tampermonkey`](https://www.tampermonkey.net/)的`@require`字段引入链接，打开匹配的任一网页，后台出现此报错。

引入的链接：`https://cdn.jsdelivr.net/npm/@wangeditor/plugin-upload-attachment@0.0.1/dist/index.min.js`

![image](https://user-images.githubusercontent.com/64892985/155847649-a187180d-3bad-4da3-9703-08ad0b8ca3ce.png)

**请问这个库支持通过CDN引入吗？** 如果不支持，是否在未来有此计划呢？

如果支持，应该如何与通过CDN引入的`wangEditor`使用[搭配使用](https://github.com/wangeditor-team/wangEditor/issues/3925#issuecomment-1050943743)呢？

十分感谢！:heart:

**Comment by wangfupeng1988** [comment]
感谢反馈，我已复现了该问题。

CDN 肯定是要支持的。不过近期我没精力做，得等有时间了再看看，具体时间不能确定。

**Comment by ZiuChen** [comment]
好的，谢谢！

**Comment by wangfupeng1988** [comment]
@ZiuChen 修复了，升级最新版本试试。

**Comment by ZiuChen** [comment]
收到，谢谢你们！
