### ISSUE TITLE
不使用post方式 put方式

### ISSUE THREAD

**Issue by Homebrew1** [wangeditor-team/wangEditor-plugin-upload-attachment#14]
改上传为put

**Comment by wangfupeng1988** [comment]
自己 fork 一下，改一改源码吧。

**Comment by Homebrew1** [comment]
不暴露一个吗

**Comment by wangfupeng1988** [comment]
其实按照 Restful API 的规范，这里就应该用 post ，而非 put 。

因为 put 是幂等的，url 中需要带 id ，指某个特定的资源。
而 post 是非幂等的，url 不用带 id ，多次请求会创建不同的资源。
