### ISSUE TITLE
模仿这个写一个新的怎么写

### ISSUE THREAD

**Issue by Homebrew1** [wangeditor-team/wangEditor-plugin-upload-attachment#15]
要一个新的icon扩展到工具栏，自定义点击事件，用vue
editorPlugin、renderElems、elemsToHtml、parseElemsHtml、menus都需要吗
 引入vue和其他组件交互、而不是和编辑器的api交互可以吗

**Comment by wangfupeng1988** [comment]
> editorPlugin、renderElems、elemsToHtml、parseElemsHtml、menus都需要吗

这要看你个人需要。首先你要了解这些东西的是干嘛的，然后看需求使用。例如 [ctrl+enter 换行](https://github.com/wangeditor-team/wangEditor-plugin-ctrl-enter) 这个插件，只需要 editorPlugin 就可以了。

**Comment by wangfupeng1988** [comment]
> 引入vue和其他组件交互

可以使用自定义事件和 vue 组件交互。

**Comment by Homebrew1** [comment]
<img width="310" alt="image" src="https://user-images.githubusercontent.com/50045583/175264512-e5093b17-3071-4b3c-bca1-854d4fc5e931.png">
比如将日期组件嵌入，点击可以修改日期，需要自己改造吗

**Comment by wangfupeng1988** [comment]
这不就是跟插入链接、修改链接一个逻辑吗。需要你自己去扩展。

**Comment by Homebrew1** [comment]
这个插入链接、修改链接是你们的逻辑，把路径贴出来

**Comment by Homebrew1** [comment]
文件路径麻烦贴一下

**Comment by wangfupeng1988** [comment]
> 这个插入链接、修改链接是你们的逻辑，把路径贴出来

https://github.com/wangeditor-team/wangEditor/tree/master/packages/basic-modules/src/modules/link/menu
