### ISSUE TITLE
上传附件之后，下载链接失效

### ISSUE THREAD

**Issue by zymylove2009** [wangeditor-team/wangEditor-plugin-upload-attachment#16]
求助！！ 上传之后利用v-html解析完之后  无法点击下载 

![Snipaste_2022-07-08_16-13-51](https://user-images.githubusercontent.com/4392771/177949103-38e3a19e-8a23-467a-afa9-7db1f5bd2dc9.png)

**Comment by wangfupeng1988** [comment]
链接在 data-link 属性中，自己增加一个 click 事件即可

**Comment by xhhaha** [comment]
确实 很难受 只能click  呼唤open 了
