### ISSUE TITLE
附件显示HTML是span，如何渲染内容，为什么不考虑直接显示a标签呢

### ISSUE THREAD

**Issue by isboyjc** [wangeditor-team/wangEditor-plugin-upload-attachment#17]
文档中描述该插件最终会解析的标签是span
在富文本编辑器内容渲染（只渲染，无编辑器）时，span标签如何处理下载
为什么不考虑直接输出a标签呢

```html
<span data-w-e-type="attachment" data-w-e-is-void data-w-e-is-inline data-link="https://xxx.com/aaa/bbb/xxx.zip" data-fileName="xxx.zip">xxx.zip</span>

```

**Comment by wangfupeng1988** [comment]
自己增加一个 click 事件即可实现点击下载

**Comment by wangfupeng1988** [comment]
使用 a 标签，会和普通链接冲突

**Comment by isboyjc** [comment]
但是这样的话通用性就小了，不是吗，因为不能够随时随地的用了
你说的冲突是和超链接混淆的情况吗，如果仅是这样的话就不用a标签而在通用性上作出让步是不是有点得不偿失呢？
假如需要把数据对接给三方，那三方同样需要处理这块逻辑。这样的话其实每次做单纯渲染时都要做处理，倒不如直接用a标签了

**Comment by wangfupeng1988** [comment]
如果给第三方，你可以自己替换为 a 标签。前提是第三方不用 wangEditor 编辑，只用于展示。

**Comment by isboyjc** [comment]
好吧。。
