### ISSUE TITLE
上传服务地址咋不行的？

### ISSUE THREAD

**Issue by ZhongChunle** [wangeditor-team/wangEditor-plugin-upload-attachment#22]
![image](https://user-images.githubusercontent.com/87836714/190569354-51e855ba-69d1-4ba3-ba9a-a8348a0daa2e.png)

![image](https://user-images.githubusercontent.com/87836714/190569415-77ddc37a-0c10-484e-a212-8c22269b9149.png)

**Comment by wangfupeng1988** [comment]
参考这个 demo 的写法吧 https://github.com/wangfupeng1988/html-wangeditor-demo/blob/main/v5-attachment.html

**Comment by ZhongChunle** [comment]
实际上上传附件的按钮是有的呢，为啥就不行呢，我在之前配置上传图片是可以的





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "wangeditor-team/wangEditor-plugin-upload-attachment"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年9月16日(星期五) 下午2:37
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [wangeditor-team/wangEditor-plugin-upload-attachment] 上传服务地址咋不行的？ (Issue #22)





 
参考这个 demo 的写法吧 https://github.com/wangfupeng1988/html-wangeditor-demo/blob/main/v5-attachment.html
