### ISSUE TITLE
富文本编辑器里面的元素没法区分点击的是哪个

### ISSUE THREAD

**Issue by LJShu** [wangeditor-team/wangEditor-plugin-upload-attachment#28]
图片  https://72cm-bucket.oss-cn-shenzhen.aliyuncs.com/uploads/web/advert/yuanlicang/1667288181103.png
使用span[data-w-e-type="attachment"] 监听点击没有用

**Comment by wangfupeng1988** [comment]
最新版已经使用 `<a>` 标签了，不适用 `<span>` 标签了

https://github.com/wangeditor-team/wangEditor-plugin-upload-attachment#%E6%98%BE%E7%A4%BA-html
