### ISSUE TITLE
报重复key  uploadAttachment

### ISSUE THREAD

**Issue by xingyu-Lu** [wangeditor-team/wangEditor-plugin-upload-attachment#29]
![image](https://user-images.githubusercontent.com/24647719/203922682-2291f32e-b42b-4213-9833-ed74b8d99a89.png)

**Comment by wangfupeng1988** [comment]
重复注册了。

可以看看注册的代码，是否执行了多遍

**Comment by xingyu-Lu** [comment]
问题是这样的，a页面有这个富文本编辑器，b页面也有这个富文本编辑器，c页面也有这个富文本编辑器，a，b，c页面是3个不同菜单进去的，目前貌似切换3次以上菜单，进去富文本编辑的页面，就会出现这个报错，在onBeforeUnmount，editor也destroy了的

**Comment by xingyu-Lu** [comment]
在每个创建富文本页面也只注册了一次attachmentModule

**Comment by wangfupeng1988** [comment]
> 在onBeforeUnmount，editor也destroy了的

跟这没关系。你监听一下 attachmentModule 这行代码，是否全局只执行一次？

**Comment by xingyu-Lu** [comment]
已解决，谢谢你

**Comment by shinchanZ** [comment]
你好，请问我在nextjs中使用也会出现这个问题，由于是服务端渲染，需要用到动态组件，不好全局注册，请问有没有什么方法能不能判断一下module有没有注册过

**Comment by yan-y** [comment]
> 

你好，这个应该怎么监听呢？

**Comment by yan-y** [comment]
> > 在onBeforeUnmount，editor也destroy了的
> 
> 跟这没关系。你监听一下 attachmentModule 这行代码，是否全局只执行一次？

你好，这个应该怎么监听呢？
