### ISSUE TITLE
L.createUploader undefined

### ISSUE THREAD

**Issue by Cesar-1e** [wangeditor-team/wangEditor-plugin-upload-attachment#3]
I did the instructions of [README-en.md](https://github.com/wangeditor-team/wangEditor-plugin-upload-attachment/blob/main/README-en.md ) but an error was presented, which I have tried many times to solve, but I have given up.
![image](https://user-images.githubusercontent.com/75588717/158005505-ee3c09ab-0114-4039-9b04-7f34e34627a1.png)

Apparently it is not loading the WangEditor Core.
Reviewing the code, the function r(336) return undefined

`
var n = {
        336: e => {
          e.exports = t
        },
        14: t => {
          t.exports = e
        },
      },
      o = {}
    function r(e) {
      var t = o[e]
      if (void 0 !== t) return t.exports
      var i = (o[e] = { exports: {} })
      return n[e](i, i.exports, r), i.exports
    }
`

Manually add the WangEditor Core, but I get other errors. This morning it reported "U" undefined, now "css" undefined.

This error occurs when I am going to attach a file

**Comment by wangfupeng1988** [comment]
You use npm install or CDN ?

**Comment by Cesar-1e** [comment]
> You use npm install or CDN ?

I tried it both on CDN and npm install. I also tried with `yarn install` and `yarn build`, but the result was the same

**Comment by wangfupeng1988** [comment]
You can check out this demo https://github.com/wangfupeng1988/webpack-wangeditor-demo

There are some codes about this plugin https://github.com/wangfupeng1988/webpack-wangeditor-demo/blob/main/src/index.ts#L25 . And some config about this plugin https://github.com/wangfupeng1988/webpack-wangeditor-demo/blob/main/src/index.ts#L60 .

`yarn install` and `yarn dev` to run in your compute, and you can upload a `mp4` attachment file.

<img width="1765" alt="image" src="https://user-images.githubusercontent.com/9583120/158018300-43adafc7-ed25-4298-a19e-0f7b8c7b4ee1.png">
 
---

PS: This demo includes some other plugins, you can ignore these.

**Comment by Cesar-1e** [comment]
It does not present an error and it executes the attachments well, however I do not handle nodejs, I handle JavaScript and html.

I tried to run it with JS and got the following error:
![image](https://user-images.githubusercontent.com/75588717/158069762-79bf33dd-2e87-4cf8-8c87-cb2dfdcba158.png)

Add the package https://www.npmjs.com/package/is-hotkey
And the scripts:

`<script src="https://cdn.jsdelivr.net/npm/@wangeditor/editor@latest"></script><script src="./core.js"></script><script src="https://cdn.jsdelivr.net/npm/@wangeditor/plugin-upload-attachment@latest"></script>`

Forked this repository to show you the code that I have implemented and the error that it logs me: [help-me-fix](https://github.com/Cesar-1e/wangEditor-plugin-upload-attachment/tree/help-me-fix) 👨‍💻

**Comment by wangfupeng1988** [comment]
I got your error, we will handle this error by this issue https://github.com/wangeditor-team/wangEditor-plugin-upload-attachment/issues/4

**Comment by wangfupeng1988** [comment]
@Cesar-1e I have resolved this error, check it in this html file https://github.com/wangfupeng1988/html-wangeditor-demo/blob/main/v5-attachment.html

**Comment by Cesar-1e** [comment]
> I have resolved this error, check it in this html file https://github.com/wangfupeng1988/html-wangeditor-demo/blob/main/v5-attachment.html

Thanks You!!
