### ISSUE TITLE
关于h5纯网页引入  plugin-upload-attachment 爆出的错误

### ISSUE THREAD

**Issue by xhhaha** [wangeditor-team/wangEditor-plugin-upload-attachment#5]
Uncaught TypeError: (0 , e.i18nAddResources) is not a function

![image](https://user-images.githubusercontent.com/40232076/158744116-e31ae5d8-a22f-4dae-9acf-2f868d511223.png)

![image](https://user-images.githubusercontent.com/40232076/158743971-b8ddfdeb-5674-4764-b709-34045a4df18e.png)

**Comment by wangfupeng1988** [comment]
参考这个 demo https://github.com/wangfupeng1988/html-wangeditor-demo/blob/main/v5-attachment.html
这个可以正常运行

**Comment by xhhaha** [comment]
我看下是不是版本号问题

**Comment by xhhaha** [comment]
上传附件和图片 默认是POST请求吗？？？？

**Comment by wangfupeng1988** [comment]
> 上传附件和图片 默认是POST请求吗？？？？

是的。如果觉得不合适，可以使用 `customUpload ` 自定义上传。

**Comment by xhhaha** [comment]
附件在预览文章的时候 无法下载

**Comment by wangfupeng1988** [comment]
@xhhaha 看这里 https://github.com/wangeditor-team/wangEditor-plugin-upload-attachment/issues/16
